spring:
  application:
    name: user-center-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/usercenter
  # session 有效时间 1 天
  session:
    timeout: 86400
server:
  port: 8080
  # 全局后台请求地址都加上前缀 /api
  servlet:
    context-path: /api
# 关闭自动驼峰命名规则（camel case）映射（默认开启）
# 即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值